Add a sanity test for Fiji startup and shutdown
This test would have caught the issue with FilamentDetector 1.0.0:

  [INFO] Running sc.fiji.InitializationTest
  [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.986 s <<< FAILURE! - in sc.fiji.InitializationTest
  [ERROR] testInitialization(sc.fiji.InitializationTest)  Time elapsed: 0.89 s  <<< ERROR!
  java.lang.IllegalArgumentException: Invalid service: sc.fiji.filamentdetector.gui.GUIStatusService
          at sc.fiji.InitializationTest.testInitialization(InitializationTest.java:38)
  Caused by: java.lang.NullPointerException
          at sc.fiji.InitializationTest.testInitialization(InitializationTest.java:38)

  [INFO]
  [INFO] Results:
  [INFO]
  [ERROR] Errors:
  [ERROR]   InitializationTest.testInitialization:38 » IllegalArgument Invalid service: sc...
  [INFO]
  [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
  [INFO]

With the forthcoming FilamentDetector 1.0.1, the test passes with a
non-JavaFX-enabled runtime.