Handle NoSuchMethodErrors also in .java 'scripts'
Our own on-the-fly compilation of .java files in ImageJ.app/plugins/
can face the same class path issues (where multiple class path
elements contain incompatible class versions) as regular plugins,
so we need to handle that, too.

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>